### ISSUE TITLE
Allow signing verifying and creating proofs of binary data as input rather than string

### ISSUE THREAD

**Issue by tplooker** [mattrglobal/node-bbs-signatures#113]
Currently the top level API for this library requires the `input messages` to be an array of strings, this should be changed to be an array of byte arrays.

**Comment by tplooker** [comment]
@mikelodder7 thoughts, this makes the API more general purpose and more inline with how other crypto library APIs?

**Comment by mikelodder7** [comment]
Yes, but we need a method of hashing to a scalar exposed like `signatureMessage.hash`

**Comment by tplooker** [comment]
1. Convert the exposed RUST FFI API to deal in byteArrays for messages, 
2. In the JS wrapper layer handle converting string to byteArrays so that there is no breaking change to the exposed API from this library.

**Comment by tplooker** [comment]
Fixed in #124
