### ISSUE TITLE
 BBS+ signatures vs CL signatures performance

### ISSUE THREAD

**Issue by picardcapt1212** [mattrglobal/node-bbs-signatures#185]
Hello, I have a question about BBS+ signature performance.
As I watched Mattr youtube and node-bbs-signatures github, I saw some comparing tables about BBS+ and CL signature.
(And also saw envernym blog post about why they moved from cl signature to bbs+)
I understand CL Signature is based on RSA so the key size or other opertaions(signing, verifying, etc) are very large and slow.

So my question is below :
I want to know how Mattr test the performance of BBS+ and CL signature. Is there a paper or a presentation you can share? Performance like Key Generation, Signing, Verifying, Proof Generation.

Thanks!

**Comment by tplooker** [comment]
Hi @picardcapt1212 you can test the performance of BBS yourself by running the benchmark tool [here[(https://github.com/mattrglobal/node-bbs-signatures/tree/master/bench) the statistics for CL signatures were shared by a community member who had measured the performance, his original presentation is available [here](https://docs.google.com/presentation/d/1JRzlzS3Y3NTm_NPzxlnud7xIDmGL_9aHHX55MMwvtlU/edit#slide=id.p1)

**Comment by picardcapt1212** [comment]
Thanks @tplooker !!
I will run the benchmark tool :)
And can I share the presentation to others?

**Comment by tplooker** [comment]
Yes you can that presentation [including my iiw presentation that references it](https://docs.google.com/presentation/d/14BXZRQ53hncwIChQ0Jbk0FZ_yy5MPK8M/edit#slide=id.g752c139538_0_197) is public
