### ISSUE TITLE
Support node versions > 14

### ISSUE THREAD

**Issue by kalinchernev** [mattrglobal/node-bbs-signatures#209]
Hello :wave: 

Opening this issue as a follow-up of https://github.com/transmute-industries/verifiable-data/issues/172 

It's related to https://github.com/mattrglobal/node-bbs-signatures/issues/182 and https://github.com/mattrglobal/node-bbs-signatures/pull/181

Any ideas or suggestions on how to approach these?

**Comment by tplooker** [comment]
@kalinchernev we support Node 16 in the [latest release](https://github.com/mattrglobal/node-bbs-signatures/releases/tag/0.15.0), closing as resolved, please re-open if you have a follow up question.
