### ISSUE TITLE
Issue with installation.

### ISSUE THREAD

**Issue by ThomasLuuu** [mattrglobal/node-bbs-signatures#213]
node-pre-gyp http GET https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.15.0/node-v108-win32-x64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.15.0/node-v108-win32-x64.tar.gz

**Comment by steffensbola** [comment]
Same here! Is this project still active?

**Comment by ThomasLuuu** [comment]
@steffensbola Do you have any solution for solving this issue? I found out that there is no file /node-v93-win32-x64.tar.gz when installing.

**Comment by ThomasLuuu** [comment]
Solving by switching to Node 16.14 => delete package-lock and yarn-lock and node-module => run yarn install => Vola!
