### ISSUE TITLE
yarn build failing

### ISSUE THREAD

**Issue by kdenhartog** [mattrglobal/node-bbs-signatures#99]
When running `yarn build` I receive the following error:

```
yarn run v1.21.1
$ yarn build:neon && yarn build:ts
$ neon build --release
neon info running cargo
error: failed to parse lock file at: /Users/kyle/Dev/demo/node-bbs-signatures/native/Cargo.lock

Caused by:
  invalid serialized PackageId for key `package.dependencies`
neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (/Users/kyle/Dev/demo/node-bbs-signatures/node_modules/neon-cli/lib/target.js:121:35)
    at step (/Users/kyle/Dev/demo/node-bbs-signatures/node_modules/neon-cli/lib/target.js:32:23)
    at Object.next (/Users/kyle/Dev/demo/node-bbs-signatures/node_modules/neon-cli/lib/target.js:13:53)
    at fulfilled (/Users/kyle/Dev/demo/node-bbs-signatures/node_modules/neon-cli/lib/target.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by kdenhartog** [comment]
@mikelodder7 or @tplooker can you take a look at this? Am I missing a dependency here or something that's causing this to fail.

**Comment by tplooker** [comment]
Can you confirm you are trying to build from the head of master?

**Comment by kdenhartog** [comment]
Yup was a fresh clone from the repository. I'm wondering if rust needs to be configured in a particular manor.

**Comment by kdenhartog** [comment]
Here's my versions:

cargo 1.36.0 (c4fcfb725 2019-05-15)
rustc 1.36.0 (a53f9df32 2019-07-03)
node --version: v10.20.1

**Comment by tplooker** [comment]
This is interesting @Liam-Tait remember the issue you encountered building rust, weren't you on the same version of cargo? @kdenhartog I believe this is a bug of cargo, if you update cargo this issue should be resolved? I am running cargo `1.41.0`

**Comment by Liam-Tait** [comment]
Yup, looks like the same issue I had. Was fixed by getting the latest version

**Comment by kdenhartog** [comment]
That fixed it. Thanks!

cargo tools at 1.36 didn't process the lock file. 1.41.0 is now. I'm not getting rust code errors from Mike's ursa fork. Seems odd though, so I'm thinking it's because of the branch I'm point at.
